ТЗ12 первая версия
NorthenGirl/java-filmorate pull request #10
Opened 2024-06-15 13:36 UTC by NorthenGirl

2024-06-17 06:30 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-06-17 06:30 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/StorageData.java
> +    long id;
Long

2024-06-17 06:30 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/likes/LikesStorage.java
> +
лишние строки

2024-06-17 06:30 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final DbFilmStorage filmStorage;
хмм, всегда желательно инжектить интерфейсы, если имплементация одна, то spring сам подтянет этот бин,  если несколько -- добавьте @Qualifier

2024-06-17 06:30 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmMapper.java
> +    Map<Long, Film> films = new HashMap<>();
модификатор доступа

2024-06-17 06:30 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmMapper.java
> +
лишняя строка

2024-06-17 06:30 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/friends/DbFrendshipStorage.java
> +        if (friendshipStatus.size() != 1) {
а если size больше 1? такое может быть? если нет, то лучше сделать
 if (CollectionUtils.isEmpty(friendshipStatus)) {

2024-06-17 06:30 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre_mpa/DbGenreStorage.java
> +    public boolean genreValidate(List<Genre> genres) {
сделайте void

2024-06-17 06:30 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre_mpa/DbGenreStorage.java
> +        return true;
и это уберите

2024-06-17 06:56 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/model/StorageData.java
> +    long id;
Поправила

2024-06-17 06:57 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/storage/likes/LikesStorage.java
> +
Удалила

2024-06-17 07:01 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final DbFilmStorage filmStorage;
Поменяла на интерфейсы, где это возможно.

2024-06-17 07:03 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmMapper.java
> +    Map<Long, Film> films = new HashMap<>();
Установила private

2024-06-17 07:04 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmMapper.java
> +
Удалила

2024-06-17 07:10 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre_mpa/DbGenreStorage.java
> +    public boolean genreValidate(List<Genre> genres) {
Поправила

2024-06-17 07:10 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre_mpa/DbGenreStorage.java
> +        return true;
Убрала

2024-06-17 12:49 UTC, ErkinKasymaliev requested changes
поправь еще один коммент пожалуйста

2024-06-17 12:49 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre_mpa/EnumStorage.java
> +public interface EnumStorage<T> {
этот момент не заметил. Удали этот интерфейс и создай для Map и Genre отдельные интерфейсы. 
у тебя в DbGenreStorage и DbMpaStorage есть методы имплементируемы и свои так делать не надо, старайся чтобы имплементация метода не содержала в себе публичные методы, которых нет в интерфейсе (к приватным метода не относится)

2024-06-17 13:36 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre_mpa/EnumStorage.java
> +public interface EnumStorage<T> {
Разделила, пришлось ещё и для дружбы выделить отдельный интерфейс, т.к. он тоже реализовывал EnumStorage.

2024-06-18 09:32 UTC, ErkinKasymaliev approved these changes
привет, работа принята!
только поправьте коммент, грамматическая ошибка

2024-06-18 09:32 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/friends/DbFrendshipStorage.java
> +public class DbFrendshipStorage implements FrendshipStorage {
Friendship

2024-06-18 14:40 UTC, merged