feat: релизовать getPopular, возвращающий список самых популярных фил…
NorthenGirl/java-filmorate pull request #21
Opened 2024-07-03 11:48 UTC by patonik

…ьмов указанного жанра за нужный год.

2024-07-03 14:43 UTC, mrchcat commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                                      @RequestParam(value = "genreId", required = false) Long genreId,
Что если придут пустые параметры или отрицательные ? На мой взгляд, имеет смысл добавить проверку.

2024-07-03 15:12 UTC, patonik commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                                      @RequestParam(value = "genreId", required = false) Long genreId,
пустые вернут все, неправильные - ничего

2024-07-03 16:09 UTC, mrchcat commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                                      @RequestParam(value = "genreId", required = false) Long genreId,
а зачем делать запрос в базу , если пришел заведомо неправильный запрос от клиента ? 
Не настаиваю, но я бы потребовал для count - больше 0 ; для genreId - больше 1, для года - после какой то там даты, когда был снят первый филь

2024-07-03 16:19 UTC, mrchcat approved these changes

2024-07-03 18:38 UTC, NorthenGirl requested changes

2024-07-03 18:38 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +        if (genreId != null) {
Судя по ТЗ {genreId}&year={year} эти два параметра должны проверяться вместе и только в этом случае будет возвращаться список, т.е. 
if (genreId != null &&  year != null) ...

2024-07-03 18:38 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getPopularFilms(Integer count, Long genreId, Integer year) {
Я бы добавила проверку перед вызовом метода поиска
if (genreStorage.getById(genreId) == null){
                throw new ValidationException("Жанра с id: " + genre.getId() + " не существует");
            }

2024-07-03 19:06 UTC, patonik commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                                      @RequestParam(value = "genreId", required = false) Long genreId,
Принято

2024-07-03 19:19 UTC, patonik commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +        if (genreId != null) {
"Фильтрация должна быть по двум параметрам.

По жанру.
За указанный год."

Это все, что говорится. У вас есть дополнительная информация?

2024-07-03 19:28 UTC, patonik commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getPopularFilms(Integer count, Long genreId, Integer year) {
Тогда запрос без фильтра будет выдавать ошибку валидации. Что если мне нужны все фильмы?

2024-07-04 15:11 UTC, NorthenGirl approved these changes

2024-07-05 10:56 UTC, merged