ТЗ 10
NorthenGirl/java-filmorate pull request #5
Opened 2024-04-18 19:15 UTC by NorthenGirl

2024-04-19 11:57 UTC, ErkinKasymaliev requested changes
привет, оставил коммент

2024-04-19 11:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public void validate(Film film) {
мне все нравится, но давай попробуем задачку со звездочкой сделать: уберем метод validate(), и всю валидацию перенесен в аннотации в модели (где то даже можно будет сделать кастомные).
Но если у тебя сроки поджимают, то без проблем, отправишь эту же работу на проверку.

2024-04-19 22:01 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public void validate(Film film) {
Переписала код с применением аннотаций.

2024-04-20 06:19 UTC, ErkinKasymaliev approved these changes
привет, круто!
работа принята

2024-04-21 09:40 UTC, merged