ТЗ 11
NorthenGirl/java-filmorate pull request #6
Opened 2024-05-13 16:17 UTC by NorthenGirl

2024-05-14 09:50 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-05-14 09:50 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ExceptionHandler.java
> +public class ExceptionHandler {
переименуй в RestControllerAdvice

2024-05-14 09:50 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler
после org.springframework.web.bind.annotation. удали везде здесь

2024-05-14 09:50 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ExceptionHandler.java
> +    /*@ResponseStatus(HttpStatus.BAD_REQUEST)
почему закоментировано? это же надо для валидационных аннотаций

2024-05-14 09:50 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ExceptionHandler.java
> +}
еще нужен хэндлер для INTERNAL_SERVER_ERROR

2024-05-14 09:50 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private  final InMemoryFilmStorage filmStorage;
надо инжектить FilmStorage и UserStorage -- это по принципу SOLID

2024-05-14 09:50 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
лишняя строка

2024-05-14 09:50 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.getFilms().get(filmId).getIdUserLike().add(userId);
в FilmStorage добавь метод
Film getFilmById(Long id)

2024-05-14 09:50 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (count == null) {
убери это условие, вместо этого в контроллере в методе сделай
public List<Film> getPopularFilms(@RequestParam(required = false, default = 10) Integer count)

2024-05-14 09:50 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.getUsers().get(userId).getFriendsId().add(friendId);
также добавь метод в UserStorage метод
User getUserById(Long id)

2024-05-14 09:50 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public void updateValidate(Film film) {
private

2024-05-14 09:50 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public void updateValidate(User user) {
private

2024-05-14 09:50 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public Map<Long, Film> getFilms() {
или private (если используется только в этом классе) или добавь в интерфейс и добавь @Override

2024-05-14 09:50 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public Map<Long, User> getUsers() {
или private (если используется только в этом классе) или добавь в интерфейс и добавь @Override

2024-05-14 09:50 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +   private final InMemoryFilmStorage inMemoryFilmStorage;
в контроллеры мы инжектим только сервисы, в сервисы storage

2024-05-14 09:50 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final InMemoryUserStorage inMemoryUserStorage;
в контроллеры мы инжектим только сервисы, в сервисы storage

2024-05-14 14:41 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/controller/ExceptionHandler.java
> +    /*@ResponseStatus(HttpStatus.BAD_REQUEST)
Экспериментировала, забыла раскомментировать

2024-05-14 15:17 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/controller/ExceptionHandler.java
> +public class ExceptionHandler {
Переименовала класс

2024-05-14 15:17 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/controller/ExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler
Удалила

2024-05-14 15:18 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/controller/ExceptionHandler.java
> +}
С эти хэндлером не проходят тесты в Postman, пришлось отказаться

2024-05-14 15:46 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +   private final InMemoryFilmStorage inMemoryFilmStorage;
добавила геттеры в сервисы

2024-05-14 15:46 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final InMemoryUserStorage inMemoryUserStorage;
добавила геттеры в сервисы

2024-05-15 12:39 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-05-15 12:39 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public InMemoryUserStorage getUserStorage() {
а вот этого не надо

2024-05-15 12:39 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userService.getUserStorage().findAll();
userService.findAll();
а в UserService.java. у тебя будет метод
```
Collection<User> findAll() {
 return inMemoryStorage.findAll();
}
```

2024-05-15 12:40 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userService.getUserStorage().findAll();
поправьте в Film тоже

2024-05-15 13:03 UTC, NorthenGirl commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public InMemoryUserStorage getUserStorage() {
Чувствовала что-то не так, но дублировать методы ещё раз показалось странным.
Поправила.

2024-05-16 10:28 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-05-16 10:29 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-05-25 09:12 UTC, merged